version: '3.1'

services:
  db-services:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: wallet-api
      MYSQL_ROOT_PASSWORD: wallet@api
    ports: 
      - 3306:3306  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080